# Generated by Django 4.0.5 on 2022-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='wage',
            field=models.IntegerField(default=15),
        ),
    ]
