# Generated by Django 4.0.5 on 2022-07-05 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreports', '0002_shiftreport_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
