# Generated by Django 4.0.5 on 2022-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftreports', '0003_shiftreport_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='total_pay',
            field=models.IntegerField(default=0),
        ),
    ]
